// flow-typed signature: 23a9ac648efb8f2360fd18c1445dc725
// flow-typed version: <<STUB>>/node-less-chokidar_v^0.1.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-less-chokidar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-less-chokidar' {
  declare module.exports: any;
}
